import { SidebarsConfig } from '@docusaurus/plugin-content-docs';

export const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};
