name: Build and test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        name: Checkout [master]
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Run Tests
        run: npm run test
