name: Create Release

on:
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        description: Increment
        required: true
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [main]
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Init npm cache
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - name: git config
        run: |
          git config --global user.name "Release Workflow"
          git config --global user.email "support@getjetstream.app"
      - name: Run Release
        run: npm run release -- "$INCREMENT" --ci
        env:
          INCREMENT: ${{ github.event.inputs.increment }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
