name: Create Release

on:
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        description: Increment
        required: true
        options:
          - patch
          - minor
          - major

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Jetstream Bot token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout [main]
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Init npm cache
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - name: install dependencies
        run: npm ci
      - name: git config
        run: |
          git config --global user.name "Release Workflow"
          git config --global user.email "support@getjetstream.app"
      - name: Run Release
        run: npm run release -- "$INCREMENT" --ci
        env:
          INCREMENT: ${{ github.event.inputs.increment }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GIT_USER: x-access-token
          GIT_PASS: ${{ steps.app-token.outputs.token }}
